### ISSUE TITLE
IBAN Passes validation when it shouldn't

### ISSUE THREAD

**Issue by JeroenHildering** [skwasjer/IbanNet#20]
This IBAN DE41500105170123456789 passes the validation but it should not:

![image](https://user-images.githubusercontent.com/17415022/75056023-686e1200-54d6-11ea-9cfa-e5a6d60070fb.png)

**Comment by skwasjer** [comment]
IbanNet does not support BBAN check digit validation out of the box. There is an [extension package](https://github.com/skwasjer/IbanNet.Extensions.Bban/tree/develop) in the works for this but especially German bank account numbers are problematic because there are tons of variations (by different banks/regions). There is currently no support for it yet.

Please create an feature request or contribute in that repo.

**Comment by skwasjer** [comment]
Added clarification in wiki:

https://github.com/skwasjer/IbanNet/wiki/IbanNet.Extensions.Bban
