### ISSUE TITLE
Senegal

### ISSUE THREAD

**Issue by ayanesuarome** [skwasjer/IbanNet#36]
Why Senegal is not a supported country by this libraries? Can you include this country?

I tried to validate two valid IBANs from Senegal and the validator fails with message:
"The country code is unknown/not supported."

IBANs:
SN70C42354573538251454437598
SN08SN0100152000048500003035

Thanks.

**Comment by skwasjer** [comment]
Is planned for future release (v5), via opt-in of a new provider. Senegal is not officially listed in SWIFT and thus originally not implemented.

https://github.com/skwasjer/IbanNet/blob/develop/src/IbanNet/Registry/Wikipedia/WikipediaRegistryProvider.cs#L870

**Comment by ayanesuarome** [comment]
Thanks for the update.

**Comment by ayanesuarome** [comment]
Ops, you are right. I need to search for a workaround for not supported countries.
Thank you a lot for the time.

**Comment by franacGIT** [comment]
Hi Martijn.

Just to inform you. I've seen that you updated pattern for Senegal (2a,22n) but seems that it's failing with "unknow country code".  
Can you confirm that this code SN08SN0100152000048500003035 is now valid?  it is ok in IBAN checker in iban.com.
Althoug maybe I'doing something wrong. This is my version Vb.Net

![image](https://user-images.githubusercontent.com/90032633/215823880-1c2c8254-557b-47da-8666-2fbf08b44b5d.png)

Thanks for your work!

Best Regards

**Comment by skwasjer** [comment]
@franacGIT you should not modify the validator options after creating the validator, because internally some references are passed along to other internal types, which will never see the 'new' options.

Instead, first create and configure `IbanValidatorOptions` and then pass it to the constructor of the validator.

**Comment by franacGIT** [comment]
Hi Martijn.

Solved! Passing to the constructor instead of assigning options did the trick. 
I found that snippet and tried to port it to vb...and almost did :). But It's not always obvious porting code from c# to vb.net.
Here is the code, maybe it's useful form somebody else.

![imagen](https://user-images.githubusercontent.com/90032633/215993923-2fd0de67-0a24-4f65-8eee-953dfb61234a.png)




Many thanks for the kind, quick, and solvent answer!

Best regards
