### ISSUE TITLE
BBAN national check digit validation

### ISSUE THREAD

**Issue by Greybird** [skwasjer/IbanNet#7]
Hello,

Thanks for this library!

Can you tell me if you plan to integrate BBAN validation (for countries having a national validation key) into this library ?
https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country lists around 17 countries having a national key. 

It would be great to have this additional layer of validation!

Arnaud

**Comment by skwasjer** [comment]
I have considered this because it would be a nice addition, and have done some initial research about 4 months ago. However, there are some concerns:
- Since BBAN is not technically a standard (https://www.iban.com/glossary), it takes extra work to do this correctly, for each country individually. I am somewhat held back by this thought, integrating it in this library.
- IbanNet currently uses SWIFT's IBAN registry to produce rules for IBAN structures per country. This will need some thought in how to reuse this if at all, or that a separate BBAN 'registry' is warranted. Probably the latter, because the IBAN registry does not have the info required: 
  - the location of (national) check digits in structure
  - type of check digits/char (whether its a constant, or which modulo function, or a CIN)
- Then, there are some design choices to be made which I still have to think about.

There are no concrete plans yet. But I don't mind leaving this issue open for a while to see if more people are interested.

**Comment by Pieter-1337** [comment]
I would be interested in the package if BBAN was supported for instance some IBAN numbers like following "BG80BNBG96611020345678" are valid on iban.com, yet need BBAN validation. Currently I am using IBAN4NET as nuget package but that seems to have been abandoned...

**Comment by skwasjer** [comment]
@Pieter-1337 This package does actually verify BBAN structures for valid characters in the specific places (bank, branch, etc), provided the SWIFT registry has this info (which is what IbanNet relies on). What it does not verify is national check digits for specific countries, because it is not very easy to find info on national or sometimes even bank specific check digit algorithms.

Can you tell me what in `BG80BNBG96611020345678` is considered wrong then? I am interested to find out.

**Comment by Pieter-1337** [comment]
@skwasjer I was bit to fast, you are correct it get's validated correctly, already implemented your package in my solution. But forgot to remove my comment ! Thx for the good package :)

**Comment by skwasjer** [comment]
@Greybird renaming to be more specific. If it does not fully cover your initial request, please let me know

**Comment by Greybird** [comment]
> @Greybird renaming to be more specific. If it does not fully cover your initial request, please let me know
It covers my initial request perfectly. I'm interested in the validation part, but far less with the structure of the BBAN. What is of interest for me is to be able to detect entry mistakes at the earliest.

**Comment by skwasjer** [comment]
Over the next period, whenever I have some time I will probably work on just the abstraction part (excluding any BBAN specific logic), and perhaps start iterating on a new v4 version that f.ex. gets rid of the `IbanValidationResult` enum. 

I also think it is wise to move the BBAN project to a dedicated repository, because it will be less stable/fully fleshed out at the start. This does allow it to be deployed to Nuget faster without the need for version bumps of the main packages. If you want I can make you a contributor on that repo too then if you are interested.

**Comment by Greybird** [comment]
I totally agree with the fact that the level of stability will not be the same on the two libs.
Your proposal is a good way to go forward ; count me in !

**Comment by skwasjer** [comment]
Moved to separate repo (still WIP at time of writing):
https://github.com/skwasjer/IbanNet.Extensions.Bban

I've also started iterating on extensibility feature in a different branch that this will have a dependency on.

**Comment by skwasjer** [comment]
Closing, see https://github.com/skwasjer/IbanNet.Extensions.Bban for status/progress
